name: 'Hello World'
description: 'Greet someone'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset."
    default: '3.8'
runs:
  using: "composite"
  steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip' # caching pip dependencies

      - uses:
        shell: bash
        run: |
          python -m pip install --upgrade pip
